//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSignal.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeSignal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   プロ生ちゃん時報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TEXT_APP_NAME {
            get {
                return ResourceManager.GetString("TEXT_APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予期せぬエラーが発生したため、終了します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TEXT_MSG_ERROR_EXCEPTION {
            get {
                return ResourceManager.GetString("TEXT_MSG_ERROR_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定ファイルの読み込みに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TEXT_MSG_ERROR_FAILED_LOAD_SETTING_FILE {
            get {
                return ResourceManager.GetString("TEXT_MSG_ERROR_FAILED_LOAD_SETTING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定ファイルの保存に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TEXT_MSG_ERROR_FAILED_SAVE_SETTING_FILE {
            get {
                return ResourceManager.GetString("TEXT_MSG_ERROR_FAILED_SAVE_SETTING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AM に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TEXT_NOTIFICATION_AM {
            get {
                return ResourceManager.GetString("TEXT_NOTIFICATION_AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PM に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TEXT_NOTIFICATION_PM {
            get {
                return ResourceManager.GetString("TEXT_NOTIFICATION_PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閉じる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TEXT_NOTIFY_ICON_MENU_CLOSE {
            get {
                return ResourceManager.GetString("TEXT_NOTIFY_ICON_MENU_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TEXT_NOTIFY_ICON_MENU_SETTING {
            get {
                return ResourceManager.GetString("TEXT_NOTIFY_ICON_MENU_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   午前・午後 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TEXT_SETTING_12_HOUR_CLOCK {
            get {
                return ResourceManager.GetString("TEXT_SETTING_12_HOUR_CLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   適用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TEXT_SETTING_APPLY {
            get {
                return ResourceManager.GetString("TEXT_SETTING_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TEXT_SETTING_CANCEL {
            get {
                return ResourceManager.GetString("TEXT_SETTING_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GUIによる通知 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TEXT_SETTING_GUI_NOTICE {
            get {
                return ResourceManager.GetString("TEXT_SETTING_GUI_NOTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TEXT_SETTING_OK {
            get {
                return ResourceManager.GetString("TEXT_SETTING_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通知頻度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TEXT_SETTING_SIGNAL_FREQUENCY {
            get {
                return ResourceManager.GetString("TEXT_SETTING_SIGNAL_FREQUENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テスト通知する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TEXT_SETTING_TEST_NOTICE {
            get {
                return ResourceManager.GetString("TEXT_SETTING_TEST_NOTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GUIの通知時間（秒） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TEXT_SETTING_TIME_TO_CLOSE {
            get {
                return ResourceManager.GetString("TEXT_SETTING_TIME_TO_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   任意の時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TEXT_SETTING_USER_TIME {
            get {
                return ResourceManager.GetString("TEXT_SETTING_USER_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TEXT_SETTING_USER_TIME_ADD {
            get {
                return ResourceManager.GetString("TEXT_SETTING_USER_TIME_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TEXT_SETTING_USER_TIME_COLOGNE {
            get {
                return ResourceManager.GetString("TEXT_SETTING_USER_TIME_COLOGNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音声による通知 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TEXT_SETTING_VOICE_NOTICE {
            get {
                return ResourceManager.GetString("TEXT_SETTING_VOICE_NOTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロ生ちゃん時報　設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TEXT_SETTING_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("TEXT_SETTING_WINDOW_TITLE", resourceCulture);
            }
        }
    }
}
